### ISSUE TITLE
Applying Code Actions upon Save does not work

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#129]
Not sure if this bug belongs to this extension or the AL extension?

https://github.com/microsoft/AL/issues/5918

**Comment by anzwdev** [comment]
That's copy of my answer from your original issue in "microsoft/AL" repository:

>My extension creates separate code action containing document edits for each missing parenthesis warning reported by the Microsoft al code analyzer. VS Code applies these edits when file is saved. Your error is thrown by AL compiler that runs in the background and rebuilds syntax tree and runs code analyzers when you edit al files. 
>I will check how VS Code sends notification about document changes to the language server when multiple code actions are applied during save. Maybe it triggers "DocumentChanged" event after each code action, so language server receivers very quickly a lot of notifications while background code analyzer is still processing al file? If that's the case, I will modify my code to report one big code action for all missing brackets and check if it helps. I will also stop creating my "Missing parenthesis" code action if you don't want to run it automatically on save as Microsoft AL Compiler also creates it and that implementation is better than mine."

**Comment by anzwdev** [comment]
I've modified code actions functionality and published a new version of the extension. 
"Add Parenthesis" code action is no longer created if "alOutline.fixCodeCopMissingParenthesesOnSave" setting is set to false as Microsoft AL Extension can now create the same code fix. Unfortunately that version cannot be run on document save, so if "alOutline.fixCodeCopMissingParenthesesOnSave" is set to true, my version of the code fix will still be created and run on document save. This change means that the code action will only be applied to whole document, so instead of reporting separate fixes for each missing parenthesis, I can create one for all of them. 

I am not able to replicate your issue, so could you check if Microsoft AL Extension still crashes on your machine after this change?
