### ISSUE TITLE
Can't Generate any files through the wizard

### ISSUE THREAD

**Issue by jigsawmegs** [anzwdev/al-code-outline#164]
Trying to create a report using the Wizard.
No file is generated.
I found the wizard is trying to create the file
`<objectId>.EftDetail.Report.al`
and not using the object number specified in the wizard
where EftDetail is the name I specified

**Comment by anzwdev** [comment]
My extension uses Waldo's CRS AL Language Extension to generate file names. What value do you have in "CRS.FileNamePattern" setting in your VS Code settings? Are you using "New AL File Wizard" or do you create your report by right clicking on a Table node in AL Outline panel and selecting "Create Report"?

**Comment by jigsawmegs** [comment]
"CRS.FileNamePattern": "<ObjectTypeShort><ObjectId>.<ObjectNameShort>.al"
I have been using the "New AL File Wizard".
Just tried the right clicking on a Table node.
Same result. Nothing generated.

**Comment by anzwdev** [comment]
Is just a problem with report wizard or all other object types are also broken? Does page or table wizard work for you? Do you have any special characters in your field names? Are you using the latest version of VS Code? Are you using Microsoft AL Extension from the Visual Studio Marketplace on manally installed *.vsix file?

**Comment by jigsawmegs** [comment]
Issue happens for all object types. 
The report would use the Gen. Journal Line table, no special characters. 
Latest VS Code. 
I am building for BC14 so have to use the vsix file from the CD iso.

**Comment by anzwdev** [comment]
I've tried to use AL Extension from BC 14 and all wizards work for me without any problems. Are you using Windows or Mac? Have you checked your "CRS.FileNamePattern" setting on both "User" and "Workspace" tabs in VS Code?  Do you have the same problem if you open different AL project or create a new one? 

You can also try to create new, clean, portable installation of VS Code and install only Microsoft AL Language, CRS AL Language Extension and mine extensions and check if you still have this problem. To do it:
 1. Download VS Code in a zip from here: [https://code.visualstudio.com/#alt-downloads](https://code.visualstudio.com/#alt-downloads)
 2. Extract zip somewhere
 3. Inside extracted VS Code folder you should see code.exe, create "data" folder there - this will tell vs code that it is portable mode and all extensions and other data shoudl be stored there instead of using your user data location
 4. Run code.exe, install all extensions that you need and test if it works

You also don't have to use VSIX from the DVD iso. You only need it if you are developing for Nav 2018, but for BC the extension installed from the VS Code Marketplace can work with all product versions. You only have to change "runtime" property in your app.json. You can find more information here: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions)

**Comment by jigsawmegs** [comment]
Its a case sensitivity issue:
The Pattern defines ObjectId
![image](https://user-images.githubusercontent.com/1054932/88615544-84a15b00-d0d5-11ea-8046-d44785ab93da.png)

But the default created pattern uses
objectId
![image](https://user-images.githubusercontent.com/1054932/88615661-c0d4bb80-d0d5-11ea-9c78-03222d1a8613.png)

Once I change the settings to use ObjectId it works.

**Comment by anzwdev** [comment]
Thank you for finding why it was not working. I've added missing error handling to the wizards, they will show an error if file cannot be created. Update will be included in the next extension release.

**Comment by anzwdev** [comment]
I've released a new version of the extension with this issue fixes.
