### ISSUE TITLE
Show AL Outline for DAL files

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#17]
Would be great to see this on DAL files as well, so when I'm looking at a base NAV CU, I have the same functionality.

**Comment by anzwdev** [comment]
AL Outline does not have any parser inside, it uses visual studio code api to get list of symbols from the language server that runs in the background. It means that it can show symbols from AL, javascript, typescript or other files as long as there is a language server for that language installed in your vs code. Nothing is shown for DAL files, because Microsoft AL extension is not returning any symbols for them.

**Comment by mjmatthiesen** [comment]
Didn't realize that it used the Language Server. I'm going to go ahead and close this up.

Thanks.
