### ISSUE TITLE
SymbolsService does not work for Codeunits with AL Language Version 3.x

### ISSUE THREAD

**Issue by DavidFeldhoff** [anzwdev/al-code-outline#171]
Hi Andrzej,

with issue #152 you fixed this already for pageextensions (and probably a few other types). But unfortunately the symbols service does not work for codeunits with the 2.x versions of your extension in combination with the AL language version 3.x.

I reproduced it with this code:
```
codeunit 50100 "Test"
{
    trigger OnRun()
    var
        A: Text;
        B: Integer;
        OK: Boolean;
    begin
        OK := OnTestSomething(A, B);
    end;
    
    var
        myInt: Integer;
}
```
![image](https://user-images.githubusercontent.com/53570297/89795774-16bf4f80-db29-11ea-99b1-bfcf3745ef3d.png)

AL Language Version: 3.0.168874
AZ AL Dev Tools: 2.08 (works with 1.0.49)

Could you have a look at it?

Best regards
David

**Comment by anzwdev** [comment]
Hi David

I can take a look but I am not sure if it makes sense to support older, manually installed Microsoft AL Extension as VS Code marketplace version is compatibile with all versions of BC. It does not support Nav 2018, so I have separate language server that works with it. 

Do you know why somebody uses that old version? I am using marketplace version of Microsoft extension with all BC versions that we have and it works without any problems. More information can be found here:
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-developing-for-multiple-platform-versions)

> The AL language extension is compatible with multiple platform versions. You can install the AL Language extension from the Visual Studio Code marketplace and use it to develop solutions for Dynamics 365 Business Central.

> The AL Language extension is not compatible with Dynamics NAV 2018 version backwards. For Dynamics NAV 2018 development, the traditional method should be used. You must install the Visual Studio Code extension from the ALLanguage.vsix file shipped on the DVD.

If Microsoft suggests to use marketplace version of their extension to develop for all versions of Business Central, then maybe we should promote that approach and keep legacy Nav 2018 support instead of trying to support all manually installed vsix files?

**Comment by DavidFeldhoff** [comment]
Hi Andrzej, just to prevent a misunderstanding from my site, I'll put it in my own words: You mean that there will be no further development for the NAV versions from our site anymore, so that we can focus on the BC versions instead?

**Comment by anzwdev** [comment]
Hi David

I mean that I have 2 separate c# projects for Nav 2018 (vsix) and BC (vs code marketplace) versions of Microsoft AL Extension. If something can be implemented for 2018 then it will be included in both versions but if something is not supported there then I will add it to BC version only.

**Comment by DavidFeldhoff** [comment]
Okay, got it. For me it's totally fine, I'm already glad that you share such awesome API :)

FYI, the one that created the issue on my repo just saw your first comment and switched to the marketplace version and it seems that his problem is solved with that suggestion. So there's no need anymore to look into it from my site. Thanks for investigating!
