### ISSUE TITLE
Object definition not available

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#194]
After downloading the bc-artefacts and moving them to the .alpackages folder (files are unblocked), I keep getting the 'Object definition not available' when navigating (Go To Definition) on the Base App symbols. Any hints on how I can navigate the base AL code though the app files (without unzipping the AL source)?

![image](https://user-images.githubusercontent.com/25268332/97085262-be262b80-161c-11eb-9c8a-bddd734999ef.png)

**Comment by anzwdev** [comment]
My extension uses Microsoft AL Extension "go to definition" functionality to go to the source code of the objects. Unfortunatley not all object types can be declared as a variable, so sometimes it is not possible to get their definitions. 
I have an idea how to make it work for enum extensions, I'll try to do it, but there will still be other object types that won't work.

**Comment by fvet** [comment]
It's not only for enum extensions, I often get a similar warning on tables, pages, codeunits, ... too.

**Comment by fvet** [comment]
@anzwdev I still struggle with opening the Base app symbols through the AL Object Browser.

I'm able to navigate (Go to definition) to a Base object (.dal file) via my table extension object, but can't see any object loaded in the AL Object Browser. Any idea how to debug to see what might be wrong?

![image](https://user-images.githubusercontent.com/25268332/115723874-b4d60b80-a380-11eb-9883-43ccd47fef8b.png)

**Comment by anzwdev** [comment]
Is it the only broken functionality? Can you create new fields using "New AL File Wizard"? Can you use "Add multiple fields" code actions? Is AL Outline panel populated when you open AL file or is it empty?

**Comment by jwinberg** [comment]
I have also been having the exact same problem for some time now , not being able to "go to definition" from AL Object Browser. 
Everything else is working flawlessly (I love this extension) like "New AL File Wizard", "Add multiple fields", AL Outline panel.

**Comment by fvet** [comment]
> Is it the only broken functionality? 
No

> Can you create new fields using "New AL File Wizard"? 
No, i get the 'No Tables Found' message

> Can you use "Add multiple fields" code actions? 
No, it does not appear as code action

> Is AL Outline panel populated when you open AL file or is it empty?
Empty

See some repro steps here:

![ALOutline](https://user-images.githubusercontent.com/25268332/116704153-5dace800-a9cb-11eb-84a5-81274e1a7613.gif)

**Comment by DavidFeldhoff** [comment]
I just noticed that these issues seem to fail since the last update of the AL Language extension which was published two days ago (version 7.1.453917).
With the previous version (7.1.441584) the most features which Frédéric explained are working for me. So just to make sure that this issue is not a mix of issues :)

**Comment by anzwdev** [comment]
Issue with wizards, code actions and al outline was caused by a bug in processing source code of a profile object. If you had a profile object in your solution, it was breaking my extension. I've fixed it and released a new version of the extension, it should work now.

@fvet, I've just relized that you are opening Microsoft_Application_18.<...>.app file. You don't see anything in the browser, because this app file does not contain any symbols. It only contains dependencies to other 2 Microsoft extensions: "System Application" and "Base Application" and has PropagateDependencies set to true, which automatically adds dependencies to these 2 applications to your project. If you want to see objects, please open one of these 2 app files.

I've also redesigned core of my extension in version 3.0.0 so now I am able to take a look at your original request of accessing definitions of all object types from app files

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension, context menu in the object browser has 2 options now: "Go to definition (project file or server definition)" and "Open definition from app file". First one runs standard VS Code "Go to definition" logic which dowloads source code of the object from the BC server. Second option extracts source code of the object from the app file if publisher of the application has set ShowMyCode property to true and if file contains source code.

**Comment by jwinberg** [comment]
thank you @anzwdev for the new feature "Open definition from app file", this helps me a lot the times when the normal go to definition doesn't work. 

I tried once again to find out what the root cause in my case was, digged around a little. It could be some sort of clash with another VS Code Extension that I had installed, namely the "AL Object Designer". If I disable that extension, then the normal Go To Definition in your extension works! I dont know the reason for this, but this is something I just found out.

**Comment by Polux-cpu** [comment]
Hello,
Thank you very much Anzwdev ! The new option "Open definition from app file" is a great addition and help every day in our work for object typed "extension".
Can you just confirm in this actual situation, it's impossible to add bakpoint in this objet because they are not taken not directly from the server ?
Thank you and have a good day.
Regards.

**Comment by anzwdev** [comment]
Hi @Polux-cpu 

Yes, I can confirm, you cannot add breakpoint to the object because it has not been opened using Microsoft AL language extension.

**Comment by anzwdev** [comment]
Hi @jwinberg

Thank you for your investigation. I'll check if I can do anything to make it work.

**Comment by jwinberg** [comment]
After more testing,.. I'm not sure but my problem could have been caused by having a multiroot workspace and mix of symbols in different .alpackages folders. Cleaning up everything (had to do the removal of .app files from File Explorer), then Reload Window (VS Code), then Download Symbols again...now things started to get in the state they should - normal Go To Definition is working!
Sorry if my earlier findings confused things more. There are so many things happening in the background (with AL Language extension) that its difficult to pinpoint problems.
Anyway I like the additional option "Open definition from app file", for times when quick lookup in source code is needed.

**Comment by anzwdev** [comment]
I've redesigned "Go To Definition" function in the last release of my extension, it should work better now.
