### ISSUE TITLE
Empty lines at end of new files

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#215]
This is more of a me issue as I am just a bit anal retentive when it comes to this.
Would be nice to have it be a config value, as I am sure some people prefer the blank line.

There are two, after added fields (here an enum) it adds a line.
It also adds on at the very end, after the final curly boy.

![image](https://user-images.githubusercontent.com/16603906/110028497-904ea300-7cf0-11eb-95c3-410870a53215.png)

**Comment by rvanbekkum** [comment]
I am not sure whether/to which extent it was intentional, but adding a newline at the end of a text file has its reasons:
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

One reason for adding a newline is to avoid diffs from showing additions to the end of the file as a change of two lines:
https://stackoverflow.com/a/22559403

I think it has partially become a habit/convention for some; for something like AL code it might not be as relevant to end the file with a new line, although there are still reasons to do it anyway.
A big part is also just personal preference; I think a good striving is to at least get it consistent in your project/team/organization.

**Comment by anzwdev** [comment]
It was not intentional, I am generating source code by writing it line by line and funtion that writes single line adds a new line at the end of the added text. I've also checked how Visual Studio generates new c# files and it also adds a new line at the end.

**Comment by mjmatthiesen** [comment]
Many things add the extra line. It's just personal preference that it wouldn't.

**Comment by fvet** [comment]
@mjmatthiesen For the last line to be removed, you can try 

`"files.trimFinalNewlines": true`

**Comment by anzwdev** [comment]
Hi

I've released a new version of the extension, you can now set `alOutline.noEmptyLinesAtTheEndOfWizardGeneratedFiles` setting to true to prevent wizards from creating empty lines at the end if generated files. I've also changed wizards logic a bit and they are no longer create empty lines betwen curly brackets at the end of files.

**Comment by mjmatthiesen** [comment]
Works great, thank you!
