### ISSUE TITLE
Add multiple fields for API pages does not respect API field properties

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#228]
When I create a page of type `API `via the `New AL File wizard`, the fields inserted on the new page receive the following settings:

- (ok) field name is camelCase
- (ok) caption contains the 'Locked = True' attribute
- (nok) ApplicationArea = All is added (I see no reason why this applies to API pages. MS does not add this in their API v2 objects neither)

Resulting file

```
page 2059394 "API Shipment"
{
    
    APIGroup = 'apiGroup';
    APIPublisher = 'publisherName';
    APIVersion = 'v1.0';
    Caption = 'aPIShipment';
    DelayedInsert = true;
    EntityName = 'entityName';
    EntitySetName = 'entitySetName';
    PageType = API;
    SourceTable = "NVT Shipment";
    
    layout
    {
        area(content)
        {
            repeater(General)
            {
                field(addresseeAddress; Rec."Addressee Address")
                {
                    ApplicationArea = All;
                    Caption = 'addresseeAddress', Locked = true;
                }
                field(addresseeAddress2; Rec."Addressee Address 2")
                {
                    ApplicationArea = All;
                    Caption = 'addresseeAddress2', Locked = true;
                }
                field(addresseeCity; Rec."Addressee City")
                {
                    ApplicationArea = All;
                    Caption = 'addresseeCity', Locked = true;
                }
```

If I add fields via the code action `Add Multiple Fields`, I get the following result

```
                field("Addressee City"; Rec."Addressee City")
                {
                    ToolTip = 'Specifies the value of the Addressee Location field';
                    ApplicationArea = All;
                }
                field("Addressee bill-to customer"; Rec."Addressee bill-to customer")
                {
                    ToolTip = 'Specifies the value of the Addressee bill-to customer field';
                    ApplicationArea = All;
                }
                field("Addressee Address"; Rec."Addressee Address")
                {
                    ToolTip = 'Specifies the value of the Addressee Address field';
                    ApplicationArea = All;
                }
```

- (nok) Field names are not camelcase.
- (nok) Tooltip should not be added (to API pages)
- (nok) Caption (with Locked = true) is missing
- (nok) ApplicationArea = All (should be removed? cfr above remark)

**Comment by anzwdev** [comment]
Thank you for reporting your issue. I've fixed it and released a new version of the extension.

**Comment by fvet** [comment]
Thanks for the fix!

I wanted to add one more remark. I'm currently using the change-case extension for camelcasing.

```
Name: change-case
Id: wmaurer.change-case
Description: Quickly change the case (camelCase, CONSTANT_CASE, snake_case, etc) of the current selection or current word
Version: 1.0.0
Publisher: wmaurer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case

```

With this extension, I get better **names** - in my opinion - than currently proposed by al-code-outline.

Same examples:

- All individual words in field names should have an uppercase (except for the first word)

field(allowlowerclassonputaway; Rec."Allow lower class on put-away") > should be `allowLowerClassOnPutAway`
field(billOfMaterialsexists; Rec."Bill Of Materials exists") > should be `billOfMaterialsExists`

- Capital words  should be full lower-cased (except for the first letter / first word)

field(eDICode; Rec."EDI Code") > should be `ediCode`
field(eORINumber; Rec."EORI Number") > should be `eoriNumber`
field(aDRClassiffCode; Rec."ADR-Classiff.Code") > should be `adrClassiffCode`

**Comment by fvet** [comment]
And what would be the community guideline towards including field captions on custom API pages? Not sure how the API consumer would use the captions anyway...

- Business Central uses the normal field captions (not the camel-cased field names)
![image](https://user-images.githubusercontent.com/25268332/115348618-1ea0ba80-a1b3-11eb-86e1-df22eac50a6e.png)

- Docs samples mentions normal field captions as well
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api

- We currently used the field captions, but with locked = true. (to avoid translation hell for APIs)

Maybe worth adding a setting to define how API field captions should be inserted?

**Comment by anzwdev** [comment]
Hi

I've modified this area and released new version of the extension. The page api fields will contain now table field captions instead of api field names to work the same way as Microsoft API v2.0 pages. There is a still posibility to use old Microsoft API v1.0 approach with api field names as captions with Locked property. To do this, you have to switch `alOutline.useTableFieldCaptionsInApiFields` vs code setting to false.

I've also changed the way in which api field names are generated from table field names. 
- If field name starts with uppercase characters, they will be all now converted to lower case, so "EDI Document" will be converted to "ediDocument". 
- If there are multiple uppercase characters and immediately after them there is lower case letter, the last upper case letter won't be conversted, so "EDIDocument" still creates "ediDocument". 
- If there is a separator (i.e. space), the next letter will be converted to upper case, i.e. "Edi document" will be converted to ediDocument.
- I am not going to convert other letters because I would like to support the case where table field name does not contain any spaces (i.e. when table field already has "ediDocument" name)
