### ISSUE TITLE
Support Copy-Paste of rows in 'New AL Table Wizard'

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#259]
During functional / technical design, consultants often describe the table schema in separate design documents (field ids, name, data type, lengths, ...) It would be beneficial if we could run the 'New AL Table Wizard' and either **copy** the rows / empty row to Excel, complete data in Excel (copying from the design document) and then **paste** the rows back in VS Code / AL Table wizard. 

Or do you have any other ideas to re-use the efforts made in the design phase?

**Comment by anzwdev** [comment]
I've released a new version of the extension, you can now copy from and paste into table wizard grid

**Comment by fvet** [comment]
Thanks a lot!

Any hints on where to put the focus while pasting? Or how the Excel should be formatted?

When i copy data below inside the ID '1' field, it seems to skip the ID column (shift columns to the left)

![image](https://user-images.githubusercontent.com/25268332/127154434-831908ed-f5c9-4b58-8040-ec916f467ac2.png)

**Comment by anzwdev** [comment]
If you paste text with TABs inside, it treats it as a table and inserts it above the record in which you are instead of pasting it inside the active cell. Just remember that the first column in the table wizard is "PK" which expects boolean values. You can see it if you enter a few fields into the wizard, select more than one row, press Ctrl+C and then paste it into excel.
