### ISSUE TITLE
[Suggestion] Fix keyword casing ?

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#262]
When looking for an AL formatter extension that fixes **keyword casing** (when converting C/AL to AL) we did not really found any decent solution. Only extension found is 'rasmus.al-formatter', but it seems no longer maintained and has some overlap with AL Code Outline/ issues, that are better implemented / solved in AL Code Outline.

Since AL Code Outline already has quit some nice commands that allows processing files (on save or via a separate commandlet), I was wondering if a 'Fix keyword casing' (for code lines only, not for properties) would fit the scope of the extension?

Ideally, we'd like 

```
IF Customer.FINDSET() THEN
  REPEAT                
  UNTIL Customer.NEXT() = 0;
```

to be formatted as

```
if Customer.FindSet() then
  repeat                
  until Customer.Next() = 0;
```

**Comment by anzwdev** [comment]
Hi

There are 2 options to implement this change. The simple one that I've implemented yesterday fixes keywords only. The advantage of this solution is that it is fast, can fix all keywords, not only these in code lines and if you want to fix one file, only that file has to be parsed. Unfortunately it won't fix function/variable names, so that's how your example will look after runing it:

```pascal
if Customer.FINDSET() then
  repeat
  until Customer.NEXT() = 0;
```

Second solution that can fix everything is more complex. It requres to compile whole project to have information about data types to be able to access function/member definition from a variable or function call in the source code. In your case I need to know data type of Customer variable and get to FINDSET function definition to know what is the real function name. It will be `FindSet` for a record variable, but if Customer is a codeunit, maybe developer has created `Findset` or `FINDSET` function? If Customer is a .net variable, then we cannot change FINDSET name because .net is case sensitive.

It can be done exactly the same way as my 'remove with' functionality, but it will be more complex and slower solution.

**Comment by fvet** [comment]
@anzwdev I think we can live with the first 'simple & fast' solution. I think there are other areas that we can benefit more from then this cosmetic part of the code ;)

**Comment by anzwdev** [comment]
I've released a new version of the extension withe the 'fast and simple' solution

**Comment by fvet** [comment]
Hmm, this has a strange side-effect ...

Using the AL tcodeunit snippet to create a new codeunit object using 'codeunit' as keyword.
Using the autocomplete to create a new codeunit variable adds 'Codeunit' as keyword. (Seems for other data types such as Label > label, ...)

![image](https://user-images.githubusercontent.com/25268332/127153262-ddbae128-b933-4df5-ae82-821b1f0049be.png)

Running it on my workspace seems to change every file...

![image](https://user-images.githubusercontent.com/25268332/127153546-79e7864d-1bea-4bcb-8d0b-94f7b69afc54.png)

**Comment by anzwdev** [comment]
Thank you for checking it. I need to investigate this issue, but it looks like I will have to add a few more lines of code to my solution.

**Comment by FSharpCSharp** [comment]
> Hi
> 
> There are 2 options to implement this change. The simple one that I've implemented yesterday fixes keywords only. The advantage of this solution is that it is fast, can fix all keywords, not only these in code lines and if you want to fix one file, only that file has to be parsed. Unfortunately it won't fix function/variable names, so that's how your example will look after runing it:
> 
> ```pascal
> if Customer.FINDSET() then
>   repeat
>   until Customer.NEXT() = 0;
> ```
> 
> Second solution that can fix everything is more complex. It requres to compile whole project to have information about data types to be able to access function/member definition from a variable or function call in the source code. In your case I need to know data type of Customer variable and get to FINDSET function definition to know what is the real function name. It will be `FindSet` for a record variable, but if Customer is a codeunit, maybe developer has created `Findset` or `FINDSET` function? If Customer is a .net variable, then we cannot change FINDSET name because .net is case sensitive.
> It can be even more complex now, when we can return complex data types from a function.
> 
> It can be done exactly the same way as my 'remove with' functionality, but it will be more complex and slower solution.

I also came across this exact point while testing the new feature. I had wondered why this functionality does not work for the system's own functions. From my point of view it would be practical if more would be corrected. I realize that this is not easy to implement because, as you already wrote, it depends on the context.

Will you still try to implement this, or will it remain with the current qick & dirty solution?

**Comment by anzwdev** [comment]
Hi @FSharpCSharp 

I need to fix quick solution first and then later I will take a look at the complex version as I agree with you that it would be nice if we can fix functions and variables names everywhere in code.

**Comment by anzwdev** [comment]
I've finally released a new version of the extension with the simple version of the fix. Now it is time to take a look at more complex solution.

**Comment by FSharpCSharp** [comment]
> I've finally released a new version of the extension with the simple version of the fix. Now it is time to take a look at more complex solution.

Sounds great! Really great with what a verve and commitment you develop this VSCode extension! 👍

**Comment by anzwdev** [comment]
I've released a new version of the extension, it contains a new set of commands to convert case of keywords, procedures and variables:
- "Fix Identifiers and Keywords Case in the Active Editor"
- "Fix Identifiers and Keywords Case in the Active Project"

They are a bit slow as they need to compile whole project first, so old, simple commands are still there:

- "Fix Keywords Case in the Active Editor"
- "Fix Keywords Case in the Active Project"
