### ISSUE TITLE
"Add multiple fields" not works with workspaces

### ISSUE THREAD

**Issue by Ponch18** [anzwdev/al-code-outline#305]
I've created a workspace for my project that includes 2 apps.
In workspace settings I've changed "al.packageCachePath" to root in order to share symbols between the two apps.

Example: 
![image](https://user-images.githubusercontent.com/51646978/145993554-e10d2bae-3250-49e5-8e7a-c092e924174b.png)

In this case the action "Add multiple fields" on page extensions not works.
Is it possible to fix?

**Comment by anzwdev** [comment]
Hi

Your problem is caused by "al.packageCachePath" setting. Loading symbols from locations other than default ".alpackages" folder is not supported yet. It is on my list of missing features, but there were always more important missing things or issues and nobody asked about it earlier. I'll add it.

**Comment by anzwdev** [comment]
I've released a new version of the extension, it now uses 'al.packageCachePath' property to load all dependencies.
