### ISSUE TITLE
Missing Parantheses for GuiAllowed

### ISSUE THREAD

**Issue by pri-kise** [anzwdev/al-code-outline#317]
Hi,
I don't know what info you are using to add missing parantheses, but it seems that the keyword/funtion `GuiAllowed` is missing.
The Intellisense of the AL Language does not add parantheses, but if I understand it correct then there should be brackets..?

**Comment by dannoe** [comment]
see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/system/system-guiallowed-method

![grafik](https://user-images.githubusercontent.com/7450586/150019089-ca7c840b-860f-4482-80ca-d31149df2a1c.png)

**Comment by anzwdev** [comment]
Hi

I am using information returned by the al compiler to apply the same logic as CodeCop when it returns A0008 warning. I compile whole al project first and then I am using semantic model built by the compiler to get information about symbol types. If symbol is a function call and parentheses are missing, I am adding them. They are not added to the GuiAllowed, because it is a property.

**Comment by dannoe** [comment]
Just for confirmation: https://github.com/microsoft/AL/issues/6908#issuecomment-1028644117
