### ISSUE TITLE
Toolset does not work with the BC20 Peview AL Compiler

### ISSUE THREAD

**Issue by Schnieringer** [anzwdev/al-code-outline#331]
I am working with the BC20 Preview AL Compiler v9.0.578036 unfortunately the toolset  does not work with this PreVersion:
![image](https://user-images.githubusercontent.com/39938430/153354236-8b842c4c-b24f-4387-ad06-c45088226a74.png)

**Comment by anzwdev** [comment]
Hi @Schnieringer 

Thank you for reporting this problem. My extension that is published in VS Code Marketplace is designed to work with the version of Microsoft AL Extension from the marketplace. I will update it to work with v9.x.x of Microsoft tools when they will be available there. Unfortunately I am not able to fix it now, because it will stop working with the current version.

**Comment by anzwdev** [comment]
I've released a new version of the extension recompiled to work with the new AL compiler v9.

**Comment by Schnieringer** [comment]
Thank you!
