### ISSUE TITLE
Go to definition doesn't work

### ISSUE THREAD

**Issue by BrianThorChristensen** [anzwdev/al-code-outline#34]
Hi,
Great job on the tools.

Just one thing.
In the object browser and project symbols, the go to definition function doesn't work for table- and pageextensions.

**Comment by anzwdev** [comment]
Thank you for posting this issue. "Go to definition" function uses AL language server "go to definition" functionality that can be invoked on a variable declaration. Page extensions, table extensions and enum extensions are not supported, because it is not possible to declare variable of that type. I have to find other way to display them.

**Comment by anzwdev** [comment]
I've modifed the extension to be able to go to definition of page/table/enum extensions from object/symbol browsers, but because Microsoft AL Language server does not support it, it only works for extension objects from the current project as there is a file that we can open.
Update has been uploaded to the Visual Studio Marketplace.
