### ISSUE TITLE
Removed Unused Variables - Local Method Parameters

### ISSUE THREAD

**Issue by jhoek** [anzwdev/al-code-outline#351]
When removing unused local method *formal* parameters, perhaps the extension could also remove the *actual* parameters from the method calls? 

```
local procedure MyFunction(MyUnusedParameter: Integer)
begin
end;

[...]

MyFunction(42);
```

would then become

```
local procedure MyFunction()
begin
end;

[...]

MyFunction();
```

instead of 

```
local procedure MyFunction()
begin
end;

[...]

MyFunction(42);
```

**Comment by anzwdev** [comment]
Hi

I am not sure that it would be a good idea as it coud lead to some undetected bugs. Imagine that instead of "MyFunction(42)" you will have "MyFunction(CreateOrderLines())" where "CreateOrderLines" creates some document lines and how many has been inserted into the database. That's why I've decided to not do it and leave code with errors so developers can review these places.

**Comment by jhoek** [comment]
@anzwdev Excellent point, I fully agree. Distinguishing between function calls (such as your CreateOrderLines()) and anything else (typically literals) would be taking things too far. Thanks for your explanation & please feel free to close this issue.
