### ISSUE TITLE
Configuration to run "fix casing of identifiers and keywords" on Code Actions On Save

### ISSUE THREAD

**Issue by ValentinoEnz** [anzwdev/al-code-outline#386]
Hi there,

would it be possible to add the `fix casing of identifiers and keywords` code-actions to the `Code Actions On Save` dropdown menu to be then run on document save.
A additional or alternative suggestion would be that you can select the option in the dropdown selection for the `Code Actions On Save` to run the actions configured for the `run code cleanup` code action.
This would be a nice enhancement if you want to be able to use specific coding guidelines and style guidelines for your projects.

**Comment by anzwdev** [comment]
Hi

Unfortunately it is not so simple. Some of these commands, including `fix casing of identifiers and keywords` need information about all symbols in the project and have to compile all files before they can start processing code even if they are changing a single file. That's why I don't want to run them on document save - it could make the whole process really slow.

**Comment by ValentinoEnz** [comment]
> Hi
> 
> Unfortunately it is not so simple. Some of these commands, including `fix casing of identifiers and keywords` need information about all symbols in the project and have to compile all files before they can start processing code even if they are changing a single file. That's why I don't want to run them on document save - it could make the whole process really slow.

Alright, thats unfortunate, but thanks for letting me know.
