### ISSUE TITLE
Account for affixes in the variable name-type completion provider(s)

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#396]
Hi @anzwdev,

Thank you for the great new completion-provider features! I think they will prove very useful!

I noticed that the completion providers drop the `_` from the names in the search, is that intentional?
We typically include a `_` directly after our ISV-prefix, to better distinguish the object name from the prefix.

Closely related question: Would it be possible to somehow include a search on the names without the (configured?) affix(es)?

Maybe there can be settings in future updates on how deep the search by the completion provider goes? For example, instead of only getting suggestions based on 'starts with' ('the current implementation') also including suggestions based on 'contains' ('of what you just typed'), or even going as far as finding the closest match for the typed string ('the most similar match(es)').

**Comment by fvet** [comment]
First of all, thanks for this great new feature. It will definitely improve the coding experience.

I agree with @rvanbekkum on the prefix thing. As an ISV developer, all our objects are prefix (ESCx), and it would be beneficial if the completion-provider would indeed allow us to ignore the prefix(es) when searching for objects.

![image](https://user-images.githubusercontent.com/25268332/191338569-6299c3c0-045a-4e71-8f30-0dee54c60b27.png)

PS: If both pages and records (table object) have a same hit / same name, wouldn't it make sense to list the 'record' as first search result? I tend to think that records are more often used than pages?

![image](https://user-images.githubusercontent.com/25268332/191339440-fda0e023-9ced-4f92-a329-4dfe3c6817ed.png)

**Comment by anzwdev** [comment]
Prefix/suffix should be ignored if you add it to the "mandatoryAffixes", "mandatoryPrefix" or "mandatorySuffix" properties in AppSourceCop.json file in your extension root folder.

I need to check the naming rule in the code analyzer to make sure that suggested variable names match the rule (i.e. if/when "_" character should be used)

I am not running any search in my code, it is done by VS Code. I only generate all possible variables based on currently available objects (1 variable for each object type + temporary versions for tables) and VS Code is doing the rest.

**Comment by rvanbekkum** [comment]
@anzwdev I found what is causing the issue for us.
Our `AppSourceCop.json` is defined like this:
```json
{
    "mandatoryAffixes": ["WSB_"]
}
```
When we drop the `_` the completion provider works, otherwise it does not.
We would like to check that the `_` is included as well though, which AppSourceCop can handle fine :):
![image](https://user-images.githubusercontent.com/7383241/191682876-62a1cc5a-6688-4871-9e0d-d3df633fbdc2.png)

Could you have a look at making it work when a `_` is included? 😊

**Comment by fvet** [comment]
@anzwdev Prefix / suffix is indeed ignored for the **current** app / folder.

Our app structure / workspace setup is composed this way:

- System / Core app with a separate prefix ESC**A** (only this prefix is mentioned in the AppSourceCop)
- License app with a separate prefix ESC**B** (only this prefix is mentioned in the AppSourceCop)
- Feature app with a separate prefix ESC**C** (only this prefix is mentioned in the AppSourceCop)

Each app thus has it's **unique** prefix to avoid naming conflicts across our apps.

---

In below scenario, I've opened a workspace containing a Core app (ESC**A** prefix) and Item Import app (ESC**I** prefix). When I reference an object (prefixed with ESCI) from the current app, the completion-provider indeed ignores the prefix (as specified in the AppSourceCop) and suggest the objects properly !

![image](https://user-images.githubusercontent.com/25268332/191688330-3de66db5-e8fe-4a16-8d9b-68f164007821.png)

However, when I reference an object (prefixed with ESCA) from outside the current app, the completion-provider does not ignore the prefix (since not specified in the AppSourceCop) and does not suggest the objects properly.

![image](https://user-images.githubusercontent.com/25268332/191688500-47db88d8-e46c-4c2a-9fcb-37282db0f157.png)

**Comment by rvanbekkum** [comment]
@anzwdev @fvet I think it is also not possible for AZ AL Dev Tool's completion provider to know what the affixes are, except for when they are set up in AppSourceCop.json in context of the current project's objects.
One solution _maybe_, not the best yet, is to add a user setting in AZ AL Dev Tools which takes a list of strings where we can put a list of affixes to be ignored.
What do you think?

**Comment by fvet** [comment]
@rvanbekkum If we could specify `ESC?` (matching ESCA, ESCB, ...) or `ESC??` (ESCBE, ESCFR, ESC-UK, ...) as setting, that would definitely do the trick. Defining an array with **all** prefixes would be hard to maintain looking at the pace new apps are released ...

We could even use this when coding against any 3rd party app, (e.g. Continia) and also include the prefixes from these apps / publishers to avoid having to type their prefixes.

**Comment by anzwdev** [comment]
I've released a new version "_" character should be properly handled now. There is also a new setting: "alOutline.additionalMandatoryAffixesPatterns". You can add all your affixes there and use '?' to specify "any character"

**Comment by fvet** [comment]
@anzwdev Cool, works like a charm. Thanks a lot !!
