### ISSUE TITLE
Xmlport / XmlPort sync with LinterCop

### ISSUE THREAD

**Issue by ChrisBlankDe** [anzwdev/al-code-outline#419]
it is not clear which notation is correct for Xmlport (XmlPort). The Autofix prefers `Xmlport `while the lintercop prefers `XmlPort`. 
regardless of which spelling is correct, we should keep the fix here the same as lintercop's preferred spelling.

Ref: https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/99

**Comment by anzwdev** [comment]
There was an issue with incorrect case of some language elements in AL extension a few months ago. It has been fixed some time ago, so I run the check again. 

My extension uses information from the AL compiler to update case of identifiers and keywords. There is a difference between object type and variable type - object types are lowercase (i.e. table or xmlport) while data types are using pascal case (i.e. Table or XmlPort). It looks like there is a problem with enum/static xml port data type that lists all available xml ports and has static methods to run them. It is reported by al compiler as "Xmlport" (i.e. Xmlport.Run() or Xmlport::xml-port-name)

**Comment by cegekaJG** [comment]
This still seems to be an issue - `LC0005` expects `XmlPort`, but the `Fix Identifiers and Keywords Case in the Active Project/Editor` commands change it to `Xmlport`.

**Comment by cegekaJG** [comment]
Can I get feedback on this? I'm getting complaints from colleagues always having to resolve warnings after cleanups.

**Comment by anzwdev** [comment]
It will be fixed in the next release.

**Comment by anzwdev** [comment]
The solution to this problem is not so simple. Microsoft compiler libraries and code completion is suggesting "Xmlport" when you use it in code as xml ports enum (Xmlport::"abc") or static type to run reports (Xmlport.Run), but is also suggesting XmlPort for variable declarations. As I mentioned above, my extension uses information provided by compiler to decide correct case for identifiers.

LinterCop rules are more consistent, but that's not what AL Compiler is sugesting. I am guessing that most people use code completion so their code has "Xmlport" in these cases. 

If I change the rules in the function, a lot of people that run "Fix Identifiers Case" command will have big commits with a lot of changes. That's why I've decided to support both cases. The default behaviour follows AL Compiler rules, but if you want to switch to LinterCop rules, then add
``` json
"alOutline.useBCLinterCopCaseRules": true
```
to your project settings.
