### ISSUE TITLE
Unable to load schema from 'aloutlinesyntax://json/appJsonSyntax.json'

### ISSUE THREAD

**Issue by zhaoyun247** [anzwdev/al-code-outline#455]
Hi, 
The latest v3.0.43 in VS code. There is an error that causes unable to view the app file in symbols browsers.
Error message
Problems loading reference 'aloutlinesyntax://json/appJsonSyntax.json': Unable to load schema from 'aloutlinesyntax://json/appJsonSyntax.json': No content.

When I roll back to the older version (v3.0.41), then the symbols browsers work flawlessly.

**Comment by salgiza** [comment]
This bug is happening to all of us in the team as well, and it happens when we open an app.json file in the editor (as soon as we close it the error goes away).

![CleanShot 2023-04-12 at 10 51 16](https://user-images.githubusercontent.com/6630306/231405271-39391b11-48a4-4cd6-9326-0468b4c6dc2c.png)

These are the details of the message in the console (I've just changed the path of the file):
```
[{
	"resource": "/path/to/project/app.json",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'aloutlinesyntax://json/appJsonSyntax.json': Unable to load schema from 'aloutlinesyntax://json/appJsonSyntax.json': cannot open aloutlinesyntax://json/appJsonSyntax.json. Detail: Unable to resolve resource aloutlinesyntax://json/appJsonSyntax.json.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

**Comment by tscottjendev** [comment]
@zhaoyun247 I have rolled back to 3.0.41 and still get the error.

**Comment by anzwdev** [comment]
I've just found that it can sometimes happen when vscode workspace contains multiple folders. A fix will be available in the next version.

**Comment by anzwdev** [comment]
Fix has been released in the latest version
