### ISSUE TITLE
[Bug] Sort procedures skips regions

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#505]
We use the ALToolBox extensions to add regions across functions, so they can be easily collapsed. Regions have the same name as the procedure name.

When using the 'Sort Procedures' action on below file ...

```
codeunit 71177454 "ESCA Data Link Dynavision" implements "ESCA Data Link Provider"
{
    Access = Internal;

    #region GetAccountName
    internal procedure GetAccountName(): Text
    begin
        exit('xxx'); // cspell:disable-line
    end;
    #endregion GetAccountName

    #region GetContainerName
    internal procedure GetContainerName(): Text
    begin
        exit('data');
    end;
    #endregion GetContainerName

    [NonDebuggable]
    #region GetStorageKey
    internal procedure GetStorageKey(): Text
    begin
        exit('xxx');
    end;
    #endregion GetStorageKey
}
```

... the function 'GetStorageKey' is moved towards the top of the file, including the start region directive. The endregion directive is however not copied. 

```
codeunit 71177454 "ESCA Data Link Dynavision" implements "ESCA Data Link Provider"
{
    Access = Internal;

    [NonDebuggable]
    #region GetStorageKey
    internal procedure GetStorageKey(): Text
    begin
        exit('xxx');
    end;

    #region GetAccountName
    internal procedure GetAccountName(): Text
    begin
        exit('xxx'); // cspell:disable-line
    end;
    #endregion GetAccountName

    #region GetContainerName
    internal procedure GetContainerName(): Text
    begin
        exit('data');
    end;
    #endregion GetContainerName
    #endregion GetStorageKey
}
```

Any chance of having this fixed?  Rule could be to include moving the #endregion (if right after the procedure declarion to be moved) only if the code to be moved includes an equivalent #region directive with the same name.

**Comment by anzwdev** [comment]
Thank you for reporting your issue. 

Before I start explaining the issues here, you should know that compiler directives and regions are not part of the syntax tree. They are "trivias" that are attached to the next syntax node in its "LeadingTrivias" property or "TrainingTrivias" if they are after the last syntax node.

There were a few problems with your example. I've fixed two issues in the code:
- closing directives after the last procedure were not detected - they are not attached to the last procedure but to the object closing bracket (last "}" character in the file)
- code was not skipping sorting when number of detected regions was different that number of endregions

There is also a problem with your example:
``` Pascal
    [NonDebuggable]
    #region GetStorageKey
    internal procedure GetStorageKey(): Text
    begin
        exit('xxx');
    end;
```
[NonDebuggable] attribute is above "#region", but this attribute is part of the procedure declaration. As a result you have region and endregion declared at 2 different levels of the syntax tree. Sort procedures is only looking at regions before and after methods and is not looking inside the declaration, so in your sample case number of detected regions does not match number of endregions.

It is a problem with all directives in the code. Opening and closing entries can be declared at different levels, which can make sorting or other code transformations impossible in some cases. That's why my current solution is very simple and only sorts procedures inside the same region. If you declare separate regions around each procedure, they won't be sorted at all.

**Comment by anzwdev** [comment]
I've just released a new version of the extension. It fixes region processing bug and adds new setting to the extension: alOutline.sortSingleNodeRegions. The default setting value is false, which means that it is only sorting procedures inside regions. When you change it to true, regions that contain single procedure only are treated as part of the procedure, so if your code has separate regions around each procedure, they will still be sorted.
