### ISSUE TITLE
Codeaction "Add multiple fields" does not respect cursor for insertion

### ISSUE THREAD

**Issue by zabcik** [anzwdev/al-code-outline#596]
**1. Describe the bug**

When using codeaction "Add multiple fields" the action does not respect cursor possition for insertion.

![AZAL_CodeactionAddMultipleFields](https://github.com/anzwdev/al-code-outline/assets/19779185/09659c4e-dde9-4d9a-838f-49bd04a05142)

**2. To Reproduce**

1. Open the page or page extension where you want to add fields.
2. Place the cursor at the desired position (before the first field, between fields, or after the last field) and observe where the code action performs the insertion.
3. Verify the insertion behavior at different positions.

**3. Expected behavior**

New field is inserted to cursor position.

**4. Actual behavior**

New field is inserted to randomly position.

**5. Versions:**

- AL Language: v14.0.1070882 (pre-release)
- Visual Studio Code: 1.91.0
- AZ AL Dev Tools/AL Code Outline: 13.67.0

**Comment by anzwdev** [comment]
Thank you for reporting this problem. It was workings this way, because all comments and empty lines are reported by the compiler as part of the syntax node below them. I've changed the logic and if cursor is before first syntax token, new field will be added before the node. Modified finctionality is available in the latest version of the extension.

**Comment by zabcik** [comment]
@anzwdev 

Thank you very much. :)
