### ISSUE TITLE
Code Fix for AL0118: Generate Procedure

### ISSUE THREAD

**Issue by rvanbekkum** [anzwdev/al-code-outline#87]
Hi @anzwdev,
Is it possible to create a code-fix for AL0118 from the tools available in your extension?
That is, a code-fix that could do something like this:
![generate-procedure](https://user-images.githubusercontent.com/7383241/75487221-50066780-59ae-11ea-86de-baa481aa20ec.gif)
I do think this could be very helpful. Of course it would be even better if Microsoft could add a code-fix for this by default.

I've looked into it already myself, but I am not quite sure how I should retrieve information on the statement (N.B., I can retrieve symbol information on the containing procedure (`DoSomething` in the example above) using your `findSymbolInRange` method, but it does not make its childsymbols available this way).
Do you think it would be difficult to implement a code-fix for this?

**Comment by anzwdev** [comment]
I don't think that it would be possible to cover all cases with my tools as I only parse current document to build syntax tree, so I don't have information about all types available in the solution. If you write something like this: 
   SayHelloWorld(TextConstCU.GetHelloWorldText()) 
then to create procedure, we have to know what type is returned from GetHelloWorldText() function that is declared in another al file.

I think that the best option would be to create a dll with code fix and make sure that it is loaded by Microsoft AL compiler. Unfortunately it looks more complicated that creating dll with code analyzers as there is no way of adding path for custom code fixes dll to the settings, so that dll would have to be copied to one of Microsoft extension folders. I was looking at standard code fix dlls some time ago and they look more complicated than code analyzers. 

Another option would be to create code analyzer dll that returns missing procedure declaration in the warning/error message and then we could access that information from type script code in vs code extension and create a code fix.

There is just one "support" problem with these dlls. They have to reference Microsoft AL compiler dlls, so they might stop working after Microsoft releases new version of AL Language extension or when developer installs older version of that extension from vsix file.

**Comment by rvanbekkum** [comment]
Thank you for your reply. I understand and agree. ;) I'll close the issue.

**Comment by DavidFeldhoff** [comment]
Hi Rob & Andrzej,

I created an extension just for that. You can find it [here](https://marketplace.visualstudio.com/items?itemName=davidfeldhoff.al-codeactions).

But as 

- my extension is quite small (probably too small) and 
- as I notice that on this extension of Andrzej were much code actions added in the last few weeks and
- I use functions of Andrzejs extension to create my codeactions

I'm considering to merge my solution to this extension as well as far as I find time to do this. 

But if you want to use it directly you may could start using mine.

Cheers,
David
