### ISSUE TITLE
Suggestion: Show local vs. global functions

### ISSUE THREAD

**Issue by epernst** [anzwdev/al-code-outline#9]
Must say that I prefer your AL-Outline to the build-in. 👍 

Generally then it would be great if it was possible to see, which procedures were defined as local and which as global. For example have the locals in a different color.

**Comment by anzwdev** [comment]
Thank you for your syggestion. At this moment my extension is not parsing documents, it asks AL language server for list of symbols. Unfortunatelly there is no information if procedure is public or local, so to add this feature I would have to implement al parser or to check if there is "local" somewhere before "procedure" symbol location. I've just created new AL issue suggesting Microsoft to switch from old SymbolInformation structures to new DocumentSymbol for document symbols and include function headers in new "details" property. If we could get full function header with "local" keyword, changing color of the outline entry would be much easier. 
You can find that issue here: https://github.com/Microsoft/AL/issues/4043

**Comment by anzwdev** [comment]
The latest version of the extension parses al files and uses different icons for global , local and test functions, test handlers, event publisher and event subscribers. It also displays parameters and local function variables and triggers inside fields and data items in tables, pages and xml ports.
